export const SITE = {
  github: "D3B-0x0",
  email: "d3b@tutamail.com",
  discord: "@pingnoob",
  linkedin: "deb69420",
  mastodon: "@deb69420",
  domain: "aboutme.debnerd.in",
  projects: [
    {
      title: "Self-Hosted Git Forge",
      description: "My own Forgejo instance with DinD-based CI/CD runners, Google & GitHub OIDC login, and push mirroring to GitHub. Friends can sign up and push code — a full self-hosted alternative to GitHub.",
      tech: ["Forgejo", "Docker-in-Docker", "CI/CD", "OIDC"],
      link: "https://git.cloud.debnerd.in",
    },
    {
      title: "VPS Edge Gateway",
      description: "Public edge for my self-hosted services — Pangolin identity-aware proxy with Gerbil + Traefik, Tailscale exit node and peer relay for the private mesh, TLS via Let's Encrypt.",
      tech: ["Pangolin", "Tailscale", "Docker"],
      link: "https://pangolin.debnerd.in",
    },
    {
      title: "Vaultwarden",
      description: "Self-hosted password manager behind Pangolin — my Bitwarden-compatible vault with encrypted off-site backups.",
      tech: ["Vaultwarden", "SQLite", "Docker"],
      link: "https://vault.cloud.debnerd.in",
    },
    {
      title: "Self-Hosted Search",
      description: "My own SearXNG instance running on the VPS with a Valkey cache — the search backend behind everything I do, with no third-party search trackers.",
      tech: ["Docker", "SearXNG", "Valkey"],
      link: "https://searx.cloud.debnerd.in",
    },
    {
      title: "Dockhand",
      description: "Container management UI for my Docker hosts — the laptop daemon plus the Azure VM over the tailnet, in one place.",
      tech: ["Docker", "Tailscale"],
      link: "https://dockhand.cloud.debnerd.in",
    },
    {
      title: "Status Page",
      description: "Public status page for everything I run — Better Uptime monitors, I get paged when something breaks.",
      tech: ["Better Uptime"],
      link: "https://uptime.debnerd.in",
    },
    {
      title: "IT-Tools",
      description: "A collection of handy developer utilities — encoders, converters, generators — self-hosted behind Pangolin.",
      tech: ["Docker", "Vue.js"],
      link: "https://tools.cloud.debnerd.in",
    },
    {
      title: "Homelab Blog",
      description: "Documentation of my self-hosting journey — what I built, what broke, and what I learned. The failures are the whole point.",
      tech: ["Astro", "Markdown", "GitHub Pages"],
      link: "https://blog.debnerd.in/",
    },
    {
      title: "Dotfiles",
      description: "Version-controlled configuration for my daily-driver Linux setup — Zsh, Hyprland, and tooling, synced declaratively via a single script.",
      tech: ["Bash", "Zsh", "Git"],
      link: "https://github.com/D3B-0x0/dotfiles",
    },
    {
      title: "Immich",
      description: "Self-hosted photo backup with no host ports exposed — terabytes of photos and growing, reachable only over my tailnet.",
      tech: ["Docker Compose", "PostgreSQL", "Tailscale"],
      link: "https://blog.debnerd.in",
    },
    {
      title: "This Website",
      description: "Started as a Figma export, rewritten to say what I actually do. Self-hosted on Forgejo with mirroring, deployed to GitHub Pages.",
      tech: ["React", "Vite", "Tailwind"],
      link: "https://git.cloud.debnerd.in/d3b/website",
    },
  ],
}
